---
- include_vars: ack.yml
- name: install ack
  tags: ack
  package: name=ack
  when: (ansible_distribution == "CentOS") or
        (ansible_distribution == "Debian") or
        (ansible_distribution == "MacOSX")

- name: ack dotfile
  template: src=roles/utilities/templates/ack.j2 dest={{ silhouette_dotfiles_path }}/.ackrc owner={{ silhouette_user }} mode=0600
